import type { PermissionDefinition } from "../types/models";

export const permissionCatalog: PermissionDefinition[] = [
  { key: "dashboard.view", label: "查看工作台", description: "访问工作台总览", group: "工作台" },
  { key: "hosts.view", label: "查看主机", description: "查看主机资产", group: "资产管理" },
  { key: "hosts.manage", label: "管理主机", description: "创建与编辑主机", group: "资产管理" },
  { key: "hosts.test", label: "测试主机", description: "执行 SSH 连通性检测", group: "资产管理" },
  { key: "hosts.operate", label: "操作主机", description: "执行主机高风险操作", group: "资产管理" },
  { key: "secrets.view", label: "查看凭证", description: "查看凭证列表", group: "资产管理" },
  { key: "secrets.manage", label: "管理凭证", description: "新增与编辑凭证", group: "资产管理" },
  { key: "secrets.use", label: "使用凭证", description: "允许业务模块解密与使用凭证", group: "资产管理" },
  { key: "secrets.rotate", label: "轮换凭证", description: "更新敏感值并记录轮换", group: "资产管理" },
  { key: "registries.view", label: "查看镜像仓库", description: "查看 Registry 列表与仓库内容", group: "交付发布" },
  { key: "registries.manage", label: "管理镜像仓库", description: "创建、编辑与删除 Registry", group: "交付发布" },
  { key: "registries.test", label: "测试镜像仓库", description: "执行 Registry 连接测试", group: "交付发布" },
  { key: "services.view", label: "查看服务定义", description: "查看服务列表、版本和实例", group: "交付发布" },
  { key: "services.manage", label: "管理服务定义", description: "创建、编辑与删除服务定义", group: "交付发布" },
  { key: "services.release", label: "执行服务发布", description: "发布与升级服务版本", group: "交付发布" },
  { key: "services.rollback", label: "回滚服务版本", description: "执行服务版本回滚", group: "交付发布" },
  { key: "terminal.open", label: "打开终端", description: "创建 WebSSH 会话", group: "运维执行" },
  { key: "docker.view", label: "查看 Docker", description: "查看节点与容器", group: "运维执行" },
  { key: "docker.manage", label: "管理 Docker", description: "创建、编辑与删除 Docker 节点", group: "运维执行" },
  { key: "docker.test", label: "测试 Docker", description: "执行 Docker 节点连通性测试", group: "运维执行" },
  { key: "docker.operate", label: "操作容器", description: "执行容器启停与重启操作", group: "运维执行" },
  { key: "nginx.view", label: "查看 Nginx", description: "查看 Nginx 节点与配置版本", group: "运维执行" },
  { key: "nginx.manage", label: "管理 Nginx", description: "创建节点与编辑配置", group: "运维执行" },
  { key: "nginx.test", label: "测试 Nginx", description: "执行配置测试", group: "运维执行" },
  { key: "nginx.reload", label: "重载 Nginx", description: "执行 Nginx 重载", group: "运维执行" },
  { key: "nginx.publish", label: "发布 Nginx 配置", description: "发布配置版本到节点", group: "运维执行" },
  { key: "nginx.rollback", label: "回滚 Nginx 配置", description: "回滚已发布的配置版本", group: "运维执行" },
  { key: "healthchecks.view", label: "查看健康检查", description: "查看服务探活与主机可用性记录", group: "运维执行" },
  { key: "healthchecks.run", label: "执行健康检查", description: "手动触发健康检查任务", group: "运维执行" },
  { key: "tasks.view", label: "查看任务", description: "查看任务中心", group: "运维执行" },
  { key: "tasks.create", label: "创建任务", description: "创建新的任务记录", group: "运维执行" },
  { key: "tasks.dispatch", label: "调度任务", description: "写入任务步骤与日志", group: "运维执行" },
  { key: "tasks.cancel", label: "取消任务", description: "取消运行中或待执行任务", group: "运维执行" },
  { key: "tasks.retry", label: "重试任务", description: "重试失败或已取消任务", group: "运维执行" },
  { key: "alerts.view", label: "查看告警", description: "查看告警事件与通知记录", group: "稳定性" },
  { key: "alerts.manage", label: "管理告警规则", description: "创建和编辑告警规则", group: "稳定性" },
  { key: "alerts.ack", label: "处理告警", description: "确认与关闭告警事件", group: "稳定性" },
  { key: "notifications.view", label: "查看通知通道", description: "查看通知通道与发送记录", group: "稳定性" },
  { key: "notifications.manage", label: "管理通知通道", description: "创建和编辑通知通道", group: "稳定性" },
  { key: "notifications.test", label: "测试通知通道", description: "发送测试通知", group: "稳定性" },
  { key: "notifications.secret.manage", label: "管理通知密钥", description: "管理通知敏感配置绑定", group: "稳定性" },
  { key: "audits.view", label: "查看审计", description: "查看审计日志", group: "安全审计" },
  { key: "exports.view", label: "查看导出", description: "查看导出任务与记录", group: "安全审计" },
  { key: "exports.create", label: "创建导出", description: "创建导出任务", group: "安全审计" },
  { key: "exports.download", label: "下载导出", description: "下载导出文件", group: "安全审计" },
  { key: "exports.unmasked", label: "下载非脱敏导出", description: "导出包含敏感明文的数据", group: "安全审计" },
  { key: "backups.view", label: "查看备份", description: "查看备份记录", group: "安全审计" },
  { key: "backups.create", label: "创建备份", description: "创建备份任务", group: "安全审计" },
  { key: "backups.download", label: "下载备份", description: "下载备份文件", group: "安全审计" },
  { key: "backups.download.unmasked", label: "下载非脱敏备份", description: "下载包含敏感明文的备份", group: "安全审计" },
  { key: "users.view", label: "查看用户", description: "查看用户列表", group: "系统管理" },
  { key: "users.manage", label: "管理用户", description: "新增与编辑用户", group: "系统管理" },
  { key: "roles.view", label: "查看角色", description: "查看角色列表", group: "系统管理" },
  { key: "roles.manage", label: "管理角色", description: "创建角色并配置权限", group: "系统管理" },
  { key: "scheduler.view", label: "查看调度任务", description: "查看定时任务配置", group: "系统管理" },
  { key: "scheduler.manage", label: "管理调度任务", description: "创建、编辑与删除定时任务", group: "系统管理" },
];

export const permissionGroups = permissionCatalog.reduce<Record<string, PermissionDefinition[]>>((acc, item) => {
  acc[item.group] = acc[item.group] ?? [];
  acc[item.group].push(item);
  return acc;
}, {});
