export const queryKeys = {
  setup: ["setup"] as const,
  me: ["me"] as const,
  dashboard: ["dashboard"] as const,
  users: (keyword: string) => ["users", keyword] as const,
  roles: ["roles"] as const,
  secrets: (keyword: string) => ["secrets", keyword] as const,
  secret: (secretId: string) => ["secret", secretId] as const,
  secretReferences: (secretId: string) => ["secretReferences", secretId] as const,
  secretReadAudits: (secretId: string) => ["secretReadAudits", secretId] as const,
  hosts: (keyword: string) => ["hosts", keyword] as const,
  host: (hostId: string) => ["host", hostId] as const,
  registries: (keyword: string) => ["registries", keyword] as const,
  registry: (registryId: string) => ["registry", registryId] as const,
  registryRepositories: (registryId: string) => ["registryRepositories", registryId] as const,
  registryTags: (registryId: string, repository: string) => ["registryTags", registryId, repository] as const,
  registryManifest: (registryId: string, repository: string, reference: string) =>
    ["registryManifest", registryId, repository, reference] as const,
  services: (keyword: string, status: string) => ["services", keyword, status] as const,
  service: (serviceId: string) => ["service", serviceId] as const,
  serviceInstances: (serviceId: string) => ["serviceInstances", serviceId] as const,
  serviceReleases: (serviceId: string) => ["serviceReleases", serviceId] as const,
  serviceHistory: (serviceId: string) => ["serviceHistory", serviceId] as const,
  serviceVersions: (serviceId: string) => ["serviceVersions", serviceId] as const,
  serviceHealthChecks: (serviceId: string) => ["serviceHealthChecks", serviceId] as const,
  serviceRollbackSuggestion: (serviceId: string) => ["serviceRollbackSuggestion", serviceId] as const,
  dockerNodes: ["dockerNodes"] as const,
  dockerNode: (nodeId: string) => ["dockerNode", nodeId] as const,
  nginxNodes: (keyword: string) => ["nginxNodes", keyword] as const,
  nginxNode: (nodeId: string) => ["nginxNode", nodeId] as const,
  nginxConfigs: (nodeId: string) => ["nginxConfigs", nodeId] as const,
  nginxOperations: (nodeId: string) => ["nginxOperations", nodeId] as const,
  resourceContext: (resourceType: string, resourceId: string) => ["resourceContext", resourceType, resourceId] as const,
  containers: (nodeId: string) => ["containers", nodeId] as const,
  containerLogs: (containerId: string) => ["containerLogs", containerId] as const,
  hostAvailability: (hostId: string) => ["hostAvailability", hostId] as const,
  notificationChannels: ["notificationChannels"] as const,
  notificationRecords: ["notificationRecords"] as const,
  alertRules: ["alertRules"] as const,
  alertEvents: ["alertEvents"] as const,
  tasks: ["tasks"] as const,
  task: (taskId: string) => ["task", taskId] as const,
  scheduledJobs: ["scheduledJobs"] as const,
  audits: ["audits"] as const,
  terminal: (sessionId: string) => ["terminal", sessionId] as const,
};
